#!/bin/zsh

# setup certificate management, letsencrypt, traefik
function setupSSL() {
  # install certificate manager
  kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml -ncert-manager
  mkdir /tmp/cluster-ssl-config && cd $!
	
}
