#!/bin/zsh

function getCertInfo() {
  local domain=$1 # required positional parameter
  local issuer=$(echo | openssl s_client -showcerts -servername ${domain} -connect ${domain}:443 2>/dev/null | openssl x509 -inform pem -noout -text | grep -i Issuer | awk -F'=' '{print $3}' | awk '{print $1,$2}' | sed s/,//g)

}

function validateDomain() {
  local domain=$1
  local reDomain="(?=^.{4,253}$)(^(?:[a-zA-Z](?:(?:[a-zA-Z0-9\-]){0,61}[a-zA-Z])?\.)+[a-zA-Z]{2,}$)"
  if [[ "${domain//reDomain/}" ]]; then
    echo "Valid $domain name."
  else
    echo "Not valid $domain name."
  fi
}

function main() {
  validateDomain $1
}

##
##	Positional parameters:
##		$1	domain name
##			ex: www.empassion.com
##				empassion.com
##				app.empassion.com
main $1
