---
##
##  Include any of the directories and files matching below
##
include:
  - ./conf.d/*.yaml
  - ./conf.d/*.yml

##
##  CLI Dependencies
##
##  Use the following yaml create a software dependcy"
##
##    - manager: {brew,apt,yum,etc}                               [REQUIRED]
##      package: package name                                     [REQUIRED]
##      options: additional arguments or options, null values ok} [OPTIONAL]
##
##  The CLI will check for and install missing dependencies when the "dependencies.init" function is run.
##
##  The yaml values are concatenated to form a command that is executed.
##
##    Example:
##      ${installer} install ${package} ${options}
##      - installer: brew
##          package: '--cask '
##      like
##      brew install
##
dependencies:
  - installer: brew
    package: yq
    comment: parse yaml
  - installer: brew
    package: fzf
    comment: fuzzy finder
