#!/bin/zsh

. ./lib/traps      # error handling / traps
. ./lib/argHandler # handle arguments and options

: '
	This is the entry point for the CLI.
	It processes the command parsiing out the following:
		resource		: the resource to interact with
    action      : the action that is being applied to the resource
		options			: additonal options that are available to modify the action
                  always preceded with double dashes (--)
                  Options are processed in "function processOptions()"

	Usage example:
		ecli dependencies init --dry-run
		  - or - 
		ecli <resource> <action> <options>
'

function buildCommand() {
  argArray=("${@:#--*}")
  optArray=(${(M)@:#--*})
  argCount=${#argArray[@]}
  runCommand="./resources"
  for ((i = 1; i < $argCount + 1; i++)); do
    runCommand="${runCommand}/${argArray[$i]}"
  done
  runCommand="${runCommand} ${optArray[*]}"
  eval ${runCommand} || printf "Could not run the command: ${runCommand}\n"
  printf "\n"
}

# execute buildcommand function
# and pass the array to it
buildCommand "$@"