#!/bin/zsh

function help.display.general() {
cat <<EOF
TODO: finish general helpfile intro

General format:
	ecli RESOURCE ACTION

where:
	RESOURCE is the resource you wish to work with
	ACTION is the action you want to talk on the above RESOURCE

Accepted options:
	--dry-run			dry run (display commands but do not execute)
	--verbose, -v		verbose output
EOF

}
function help.display.commands() {
commandArray = commandArray(resources)
cat << EOF

EOF
}