#!/bin/zsh

. ./lib/ioScreen
##
##	check if a google api is enabled
##
##	positional arguments:
##    $1  the api name you are searching for
##		$2	enable if not already enabled	[OPTIONAL]
##			accepts the following:
##				0 or false		do not enable just test	[DEFAULT]
##				1 or true		enable if not already enabled
##
##    example usage:
##      check.enabled compute.googleapis.com 1
##        This would check if the compute api and enabled and enable it if not
##
function apiCheckEnabled {
  local api=$1
  case $2 in
  1 | true)
    enable=1
    ;;
  0 | false)
    enable=0
    ;;
  *)
    if [ ${#2} -eq 0 ]; then # if $2 is null that's ok
      enable=0               # do not enable
    else                     # if $2 is not null but not a recognized value
      ioScreen.outWarn "Positional argument #2 not recognized: ${2}\nMust be 0, false, 1, true, or empty\n\nUsing default and will not enable the API."
    fi
    ;;
  esac
  local apiEnabled=$(gcloud services list --project common-devops-0605 --enabled --filter="config.name=${api}" --format='value(config.name)' | wc -l | tr -d '[:space:]')
  echo $apiEnabled
  if [ ! ${apiEnabled} -eq 0 ]; then
    apiEnabled="true"
  fi
}
