#!/bin/zsh

: '
	Helpful functions to detect things like: arch, OS, etc
'

##
##  TODO: Detect OS
##    Unsure if this is useful.  Maybe.  thought so originally - but probably not.
##
function TODO.detect.os {
  local osType=$(echo ${OSTYPE:l} | tr -d '[:digit:]._-')
  local unameResult=$(echo ${uname:l})
  printf "${osType}\n"
  printf "${unameResult}\n"
}

##
##  Detect if zsh is installed, where, and current config pointer value
##
function detect.zshInstall {
  local zshBin=$(command -v zsh) || zshBin="UNDEF"
  if ! [[ ${zshBin} == "UNDEF" ]]; then
    echo $?
  fi

}

##
##  Checks to see if a script was called directly
##  Arguments:
##    $1 = message to output if script is called directly
##
function detect.directCall() {
  if [[ ! $SHLVL -gt 2 ]]; then
    ##printf "\nThis script should not be called directly.\n"
    sourced=0
  fi
}
