#!/bin/zsh
: '
	Gets configuration items from the config.yaml file and returns an array
'

##	normalizes a yaml file
##		positional arguments:
##			$1 : relative or absolute path to the yaml file
function getConfig.normalizeYAML() {
  local file=$1
  if [ ! -f ${file} ]; then
    echo "File not found!" >&2
    exit 1
  fi
  # strip extra chars, make unixy. just in case
  if [ command -v dos2unix ]; then
    dos2unix ${file}
  fi
  # convert each tab into 2 spaces
  expand -t 2 ${file}
}

# builds an array from config.yaml
function getConfig.configArray() {

}

# TODO: when needed
# builds an associative array
# function configAssocArray() {

# }
