#!/bin/zsh
. ./lib/libConfig 	# interactions with config.yaml
. ./lib/ioScreen	# screen i/o

: '
	Initialization functions
	check installations
	load configs
'

##
## check for dependencies
##
function checkDependencies {
  declare -A dependencies
  dependencies[brew]="NONINTERACTIVE=1; curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh >/dev/null"
  dependencies[yq]="brew install yq >/dev/null"
  for key value in ${(kv)dependencies}; do
    if command -v ${key} 2>&1 1>/dev/null; then 
      ioScreen.outInfo "Dependency ${white}${key}${green} is already installed."
    else
      ioScreen.outWarn "Installing dependency ${white}${key}${noColor}."
      eval ${value}
    fi
  done
}

ioScreen.stdHeader "Installing missing dependencies"
checkDependencies