#!/bin/zsh
#  TODO: this is a good idea,  every evem should be kept in a history file so that it can be rolled back
: ' 
rollback events based on a log
event:
- action`1
  status
- action 2
` status
'