#!/bin/zsh

noColor='\033[0m'
black='\033[0;30m'
red='\033[0;31m'
green="\033[0;32m"
brown='\033[0;33m'
blue='\033[0;34m'
purple='\033[0;35m'
cyan='\033[0;36m'
lightGray='\033[0;37m'
darkGray='\033[1;30m'
lightRed='\033[1;31m'
lightGreen='\033[1;32m'
yellow='\033[1;33m'
lightBlue='\033[1;34m'
lightPurple='\033[1;35m'
lightCyan='\033[1;36m'
white='\033[1;37m'

##  3/25/2023 : adding aliases to support backward compaitibilty due to new function naming convention
alias outInfo=ioScreen.outInfo
alias outWarn=ioScreen.outWarn
alias outError=ioScreen.outError

# displays an info message to the console
# 	$1 = message
function ioScreen.outInfo {
  printf "${green}[ ${lightGreen}INFO ${green}]\t${1}${noColor}\n"
}

function ioScreen.outWarn {
  printf "${green}[ ${yellow}WARN ${green}]\t${1}${noColor}\n"
}

##
## Error handling routine
## use with:
##  trap 'outError $? $LINENO' ERR
## takes 2 positional parameters
##  $1 error exit code
##  $2 line number
##
function ioScreen.outError {
  printf "${red}[ ${lightRed}ERROR ${red}]${noColor}\tStatus Code: ${1}\n\t\tLine Number: ${2}\n\t\tExiting script.\n"
  exit $1
}

##  Display a seperator that is the full width of the terminal
#
##  Accepted Arguments:
##    $1    symbol to use for line
##            pass a single character to positional argument $1
##            to define the character used to create the line
##
##  Usage Example:
##    draw.horizontal.seperator +  # creates a horziontal line made of +
function ioScreen.horizontal.seperator {
  lineChar=${1}
  if [[ -z ${lineChar} ]]; then
    lineChar="-"
  fi
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' ${lineChar}
}

function ioScreen.stdHeader {
  local headerText=${1} # text to display in the header
  if [[ -z ${2} ]]; then
    local optChar='-'
  else
    local optChar=${2}
  fi
  ioScreen.horizontal.seperator ${optChar}
  printf "\t${headerText}\n"
  ioScreen.horizontal.seperator ${optChar}
  printf '\n'
  unset headerText
}
function ioScreen.outError {
  printf "${red}[ ${lightRed}ERROR ${red}]\t${1}\n 
    \t\tLine Number: ${2}\n
    \t\tExiting script.${noColor}\n"
  exit 1
}
