#!/bin/zsh
: '
	Standard functions that are useful before running a script
	or at the time of execution
'

##
##  Checks to see if a script was called directly
##  Arguments:
##    $1 = message to output if script is called directly
##
function directCall() {
  local message=$1
  if [[ ! $SHLVL -gt 2 ]]; then
    printf "\nThis script should not be called directly.\nPlease use:\n\t${message}\n\n"
    exit 1
  fi
}
